language: node_js
node_js: '8'
before_script: npm install -g wspackager
script: wspackager
branches:
  only: master
git:
  depth: 5
env:
  global:
  - IDENTIFIER=com.clanunknownsoldiers.plugin.theme.tar
  - FTP_HOST=ftp://thunderstorm.unkso.com
  - secure: EK25N9h9MPWDjoZVgs0mJzndHQdQXm0RXbHlv9D58gkw7d6Dulpu8QpVsbhP9C6swVNAew/2BckJ+jb0+uwf649i3Gc75VsZvNPV5IVwcmk4lI6JSUnH1T5fKoixvm92gsT1aOtpIc9k13UtKOyf0zAdk3x+YF7FU528oJfjfLeCg7AIiYDmLQrxesK+3yGSeek6T6sp9fykZ/egg8BA3HFKqTYVQrkSDssJLCwOSyhK4Fkn5ANna8dOOdBMIX5Q1+fqag79uI1FPewQ8uBLdVLXDhVfyQucJl2SDv9IaMB/Nb9l/0fzOXEMG5EtX8KnZVNSEUCKJGAkz5LUVksXKsqFBMNWwazpCc5rn98roY8WKDMziGvMe4BQZ5z9QT/hJosPVKaD0WY7b6ctJxTDxlhzbWtrMtZ+qL/mZHJstOOoTz1gjQTxq1AwWZa8wkU+CAaQb39BXCFWEpfht+Fe2+jqivUxeNIV+iLSQrqYmB/aiRN/zGZtTkX51dhDsXQjBQqM9WBdrfMIV7GYvcu6oNBUGyEYsKN2EvkfcjPFxLcXlvqChYjCstq9iOs0DhjdVUa9CwsBI40GKR+J/EG5Tpp3Eip9UYloL9e5r3iBymt6Zgdpt6YSrzTNHV+NGGMp7bn2mWSb6r8asQ0Z/IfES/RTzLLoA6ZjJkOkYrQB+0c=
  - secure: F23CaCs+0/TTuGDlxB8oVoW3ELkXWuzIhu28Jf5pIEkhRFWfu9wsKPL0bRxGMZyLfZ2mAjXENfNlaV1anQb/dvynXg6DIukBKDjeNHR3Fxz6hvGq9mWbymySaZJaJTO7V3vwTMkn5XxLt8tCFSkDhm7w3T+34hyNNJt7Dbnm3/8nOPQOpz36jm4HCTWN3kNkrpnTrRptzRFIDgCeovEZwLoe94Dto3MWvP5CjM2teBXNOQeXlT4dr/yv0JwGczIVxENJ4+DvrWkeRF/HGpa/xeD8m57QkWf1ZCadGs3vf5m7vWTPLeDSfr9bK9bjl8qeXHFFJeD2vcYA6eeGSQK2aVfg4bTAqRSRFP7YpQxWMxZLgam6rFmTQaWCbTtqV/ewp81awCsU3rIlGsHqDBiM54cZITEc1znsBypaIAjotZouZ6NzY+PkTu20d6q6WEhnVpxXAYYzicLplok6OsxJ3eEe9JlLc4WxgjVqBAsDGbePoz8eVotNIQtVqKsiLLbGY0yR3o9dHxwswAgB95PA1kh12q72LXjds+D2/ulRFSzQBS8kQ0IHaDQpftWNfTt7cAgXOb+3EgG6N49SmfZWoJdVip4Cmbh2rgfI6Rv6u32fcoa06XoIjrX9rxUCg9eU8ZmKvJLeNo4BDEteuA0QVIt4Mh1U84OeD+8GA8hGz9U=
notifications:
  email: false
after_success: curl --ftp-create-dirs -T $IDENTIFIER -u $FTP_USER:$FTP_PASSWORD $FTP_HOST
